# Generated by Django 5.1.2 on 2024-10-28 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=255)),
                ('thematic_unit', models.CharField(max_length=255)),
                ('knowledge_objectives', models.TextField()),
                ('skills', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('project_url', models.URLField()),
                ('game_type', models.CharField(max_length=100)),
                ('age_range', models.CharField(max_length=50)),
                ('content_classification', models.CharField(max_length=50)),
                ('game_genre', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('informative_text', models.TextField(max_length=500)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('curriculum_base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='games.curriculumbase')),
                ('photo_files', models.ManyToManyField(related_name='games', to='games.photo')),
            ],
        ),
    ]
